site_name: Consolidated Storage on Nutanix
site_url: https://github.com/nutanix-japan/Consolidated_Storage_Bootcamp_Material
site_author: Lakshmi Balaramane

# Repository

repo_name: nutanix-japan/Consolidated_Storage_Bootcamp_Material
repo_url: https://github.com/nutanix-japan/Consolidated_Storage_Bootcamp_Material

# Copyright
copyright: Copyright &copy; 2016 - 2022 Nutanix APAC Enablement Practice

# Configuration

theme:
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.footer
  # - navigation.sections # leave this commented for sections
  # - navigation.expand
  - navigation.top
  - navigation.integrate
  - search.highlight
  - search.suggest
  - toc.follow
  - content.code.copy
  
  palette:

    #Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
    - search

nav:
    - Home: index.md
    #- Initial NUS Deployment:
      #- 'Files - Deploy Nutanix Files': files_deploy/files_deploy.md
      #- 'Objects - Deploy Nutanix Objects': objects_deploy/objects_deploy.md
      #- 'Files & Objects - RBAC on Files and Objects': rbac/rbac.md
    #- Start Consuming Storage Services:
      #- 'Files - Create SMB Share': files_smb_share/files_smb_share.md
      #- 'Volumes - Deploy Nutanix Volumes': volumes_deploy/volumes_deploy.md
      #- 'Objects - Buckets & Users Management': objects_buckets_users_access_control/objects_buckets_users_access_control.md
    - Migrating from existing File Share:
      # - 'Files - Share Migration': files_migrate/files_migrate.md
      - 'Move - Share Migration': files_migrate/files_migrate_move.md
    - Data Visibility & Intelligence (A) - Data Lens:
      - 'Deploy Data Lens': datalens_deploy/datalens_deploy.md
      - 'Anomaly Detection': datalens_anomaly/datalens_anomaly.md
      - 'Ransomware Protection': datalens_ransomware/datalens_ransomware.md
      - 'Permission Monitoring': datalens_permission_monitoring/datalens_permission_monitoring.md
    # - Data Visibility & Intelligence (B) - File Analytics:
    #   - 'Enable File Analytics': file_analytics_deploy/file_analytics_deploy.md
    #   - 'Anomaly Detection': file_analytics_anomaly/file_analytics_anomaly.md
    #   - 'Ransonware Protection': file_analytics_ransomware/file_analytics_ransomware.md
    - Data Protection and Lifecycle Management:
      - 'Files - Replication': files_replication/files_replication.md
      - 'Files - Tiering': files_tiering/files_tiering.md
    # - 'Optional Labs':
    #   - 'Files - Create NFS Share': files_nfs_export/files_nfs_export.md
    #   - 'Files - Expand Files Cluster (Not applicable to single node cluster)': files_expand_cluster/files_expand_cluster.md
    #   - 'Files - Enable Files Multiprotocol': files_multiprotocol/files_multiprotocol.md
    #   - 'Objects - Access Objects from CLI and Scripts': objects_cli_scripts/objects_cli_scripts.md
    #   - 'Objects - Multi-cluster': objects_multi_cluster/objects_multi_cluster.md


